const CHANGE_NEWPASSWORD = 'boilerplate/NewPassword/CHANGE_NEWPASSWORD';
const CHANGE_CONFIRMPASSWORD = 'boilerplate/NewPassword/CHANGE_CONFIRMPASSWORD';
const SEND_NEWPASS = 'boilerplate/NewPassword/SEND_NEWPASS';
const CHANGE_FORM_INPUT = 'boilerplate/EmailConfirmed/CHANGE_FORM_INPUT';
const MEMBERSHIPS_LOADED = 'boilerplate/EmailConfirmed/MEMBERSHIPS_LOADED';
const MEMBERSHIPS_LOAD = 'boilerplate/EmailConfirmed/MEMBERSHIPS_LOAD';
const USER_TYPE = 'boilerplate/Memberships/USER_TYPE';
const SEND_TYPE_PAGES = 'boilerplate/Memberships/SEND_TYPE_PAGES';
const CHANGE_USERNAME = 'boilerplate/LoginPage/CHANGE_USERNAME';
const CHANGE_PASSWORD = 'boilerplate/LoginPage/CHANGE_PASSWORD';
const SEND_USERNAMEANDPASS = 'boilerplate/LoginPage/SEND_USERNAMEANDPASS';
const FORGOTPASS_USERNAME = 'boilerplate/ForgotPassword/FORGOTPASS_USERNAME';
const FORGOTPASS_SEND = 'boilerplate/ForgotPassword/FORGOTPASS_SEND';
const VERIFY_EMAIL = 'boilerplate/EmailConfirmed/VERIFY_EMAIL';
const CHANGE_USERNAMEREG = 'boilerplate/Registration/CHANGE_USERNAMEREG';
const CHANGE_EMAIL = 'boilerplate/Registration/CHANGE_EMAIL';
const CHANGE_PASS = 'boilerplate/Registration/CHANGE_PASS';
const CHANGE_REPEATPASSWORD = 'boilerplate/Registration/CHANGE_REPEATPASSWORD';
const SEND_REGISTRATION = 'boilerplate/Registration/SEND_REGISTRATION';


export {
  CHANGE_USERNAMEREG,
  CHANGE_NEWPASSWORD,
  CHANGE_CONFIRMPASSWORD,
  SEND_NEWPASS,
  CHANGE_FORM_INPUT,
  MEMBERSHIPS_LOADED,
  MEMBERSHIPS_LOAD,
  USER_TYPE,
  SEND_TYPE_PAGES,
  CHANGE_USERNAME,
  CHANGE_PASS,
  SEND_USERNAMEANDPASS,
  FORGOTPASS_USERNAME,
  FORGOTPASS_SEND,
  VERIFY_EMAIL,
  CHANGE_EMAIL,
  CHANGE_PASSWORD,
  CHANGE_REPEATPASSWORD,
  SEND_REGISTRATION
};
